version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /ANOTHER_ld_pruning.wdl
    testParameterFiles:
      - /test.json
  - subclass: CWL
    primaryDescriptorPath: /CWL/staar_workflow.cwl
